### ISSUE TITLE
Build Frontend problem

### ISSUE THREAD

**Issue by vivianTan7** [varapp/varapp-frontend-react#1]
Hi,

When I try to build frontend, I got the following errors, can you provide some information on how to solve this, thanks.

varapp-frontend-react-master vivian$ gulp build
[17:03:22] Using gulpfile ~/Desktop/varapp_original/varapp-frontend-react-master/gulpfile.js
[17:03:22] Starting 'html'...
[17:03:22] Starting 'json'...
[17:03:22] Starting 'config'...
[17:03:22] Starting 'css'...
[17:03:22] Starting 'sass'...
[17:03:22] 'sass' errored after 33 ms
[17:03:22] TypeError: glob pattern string required
    at new Minimatch (/Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/node_modules/gulp-ruby-sass/node_modules/minimatch/minimatch.js:116:11)
    at setopts (/Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/node_modules/gulp-ruby-sass/node_modules/glob/common.js:113:20)
    at new GlobSync (/Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/node_modules/gulp-ruby-sass/node_modules/glob/sync.js:39:3)
    at Function.globSync [as sync](/Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/node_modules/gulp-ruby-sass/node_modules/glob/sync.js:25:10)
    at /Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/node_modules/gulp-ruby-sass/index.js:68:21
    at Array.forEach (native)
    at Object.gulpRubySass (/Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/node_modules/gulp-ruby-sass/index.js:67:10)
    at Gulp.<anonymous> (/Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/gulpfile.js:109:17)
    at module.exports (/Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/node_modules/orchestrator/index.js:273:3)
[17:03:22] Finished 'json' after 268 ms
[17:03:22] Plumber found unhandled error:
 Error: Error: File not found with singular glob: /Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/app/bower_components/jquery-ui/themes/smoothness/jquery-ui.css
[17:03:22] Plumber found unhandled error:
 Error: Error: File not found with singular glob: /Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/app/bower_components/components-font-awesome/css/font-awesome.min.css
[17:03:22] Plumber found unhandled error:
 Error: Error: File not found with singular glob: /Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/app/bower_components/jquery-ui/jquery-ui.min.js
[17:03:22] Finished 'config' after 529 ms
[17:03:22] all files 49.88 kB
[17:03:22] Finished 'css' after 612 ms

Already installed sass
varapp-frontend-react-master vivian$ sass -v
Sass 3.4.22 (Selective Steve)

Thank you.

**Comment by jdelafon** [comment]
Hi, 
It looks like a new version of gulp-ruby-sass that functions a bit differently. What is the output of "npm list --depth 0" ?
You can try "npm install --save-dev gulp-ruby-sass@0.7.1" to force the version to 0.7.1 (mine). 
Tell me if it works. If it does I'll patch it today.

Is there a reason why you need to build it from source? It should work fine with the precompiled JS bundle: 
https://github.com/varapp/varapp-frontend-react/releases

Related issues (for my own record):
http://stackoverflow.com/questions/32967345/typeerror-glob-pattern-string-required
https://github.com/sindresorhus/gulp-ruby-sass/issues/275

**Comment by vivianTan7** [comment]
It works with the gulp-ruby-sass@0.7.1, thanks.

however Still got the following error:

[11:40:46] Plumber found unhandled error:
 Error: Error: File not found with singular glob: /Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/app/bower_components/jquery-ui/themes/smoothness/jquery-ui.css
[11:40:46] Plumber found unhandled error:
 Error: Error: File not found with singular glob: /Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/app/bower_components/components-font-awesome/css/font-awesome.min.css
[11:40:46] Plumber found unhandled error:
 Error: Error: File not found with singular glob: /Users/vivian/Desktop/varapp_original/varapp-frontend-react-master/app/bower_components/jquery-ui/jquery-ui.min.js

any ideas?

Regards

**Comment by jdelafon** [comment]
Yes, the file "bower.json" is missing an entry for jquery-ui. If you want a quick fix you can add this line to "dependencies" in "bower.json", then run "bower install" again:

```
"dependencies": {
    "jquery": "~1.11.1"
    "jquery-ui": "~1.11.2",
    ...
}
```

**Edit**: This one is also missing:

```
"components-font-awesome": "^4.6.3",
```

Both are for igv.js to work.

**Comment by jdelafon** [comment]
This one is also missing:

    "components-font-awesome": "^4.6.3",

**Comment by jdelafon** [comment]
I pushed the necessary changes: https://github.com/varapp/varapp-frontend-react/commit/a186a448875e6d237f7d03c4e9e87f758aa8be44

The repo suffered from missing synchronization between it and the dev Gitlab instance, but from now on, development will be pushed directly to Github. I am checking now that everything else is all right.

**Comment by vivianTan7** [comment]
works perfectly now, thanks
